### ISSUE TITLE
有没有 基于这个脚手架 开发的实际项目？想学习一下

### ISSUE THREAD

**Issue by a410202049** [bigTig/react-taroify-ts#1]
有没有 基于这个脚手架 开发的实际项目？想学习一下

**Comment by lkfeng2016** [comment]
实际项目是公司的哦，不对外哦发自我的手机-------- 原始邮件 --------发件人： "kerry.gao" ***@***.***>日期： 2023年8月11日周五 17:22收件人： bigTig/react-taroify-ts ***@***.***>抄送： Subscribed ***@***.***>主    题： [bigTig/react-taroify-ts] 有没有 基于这个脚手架 开发的实际项目？想学习一下 (Issue #1)
有没有 基于这个脚手架 开发的实际项目？想学习一下

**Comment by a410202049** [comment]
那写个 demo也行啊 比如 api调用。api目录文件里面都是空的 都不知道 怎么定义

**Comment by bigTig** [comment]
有空可以搞一个 @a410202049 周末先

**Comment by bigTig** [comment]
加了个简单的例子 @a410202049 你可以看看，有事再交流
